name: Tests
on: push
jobs:
  tests:
    name: Run tests with Google Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Google Test
        run: |
          sudo apt-get install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib
      - name: Build tests executable
        run: |
          cmake -B./cmake-build-debug -H./
          cmake --build cmake-build-debug/ --target 3a_ecc_cpp_tests
      - name: Run tests executable
        run: ./cmake-build-debug/3a_ecc_cpp_tests